import { INIT_SHAPE_POINTS } from "./RECT_DATA_INIT";

export const RECT_DATA_INIT_L_1 = [
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    xGroup: 0,
    yGroup: 0,
    width: 1800,
    height: 640,
    fill: null,
    // fill: "grey",
    stroke: "black",
    strokeWidth: 1,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-de-tablero-de-madera.png",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig1",
    name: "fig1",
    textData: [
      {
        visible: true,
        rotation: 0,
        text: "Text",
        position: 0,
        name: "textTopWidthRef",
      },
      {
        visible: true,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: true,
        rotation: 0,
        text: "Text",
        position: 2,
        name: "textBottomWidthRef",
      },
      {
        visible: true,
        rotation: -90,
        text: "Text",
        position: 3,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    xGroup: 0,
    yGroup: 0,
    width: 1800,
    height: 640,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 1,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-de-tablero-de-madera.png",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig2",
    name: "fig2",
    textData: [
      {
        visible: true,
        rotation: 0,
        text: "Text",
        position: 0,
        name: "textTopWidthRef",
      },
      {
        visible: true,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: true,
        rotation: 0,
        text: "Text",
        position: 2,
        name: "textBottomWidthRef",
      },
      {
        visible: true,
        rotation: -90,
        text: "Text",
        position: 3,
        name: "textLeftHeighthRef",
      },
    ],
  },
];

export const RECT_DATA_INIT_L_2 = [
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    xGroup: 0,
    yGroup: 0,
    width: 1200,
    height: 640,
    fill: null,
    // fill: "grey",
    stroke: "black",
    strokeWidth: 1,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-de-tablero-de-madera.png",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig1",
    name: "fig1",
    textData: [
      {
        visible: true,
        rotation: 0,
        text: "Text",
        position: 0,
        name: "textTopWidthRef",
      },
      {
        visible: true,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: true,
        rotation: 0,
        text: "Text",
        position: 2,
        name: "textBottomWidthRef",
      },
      {
        visible: true,
        rotation: -90,
        text: "Text",
        position: 3,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    xGroup: 0,
    yGroup: 0,
    width: 2440,
    height: 640,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 1,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-de-tablero-de-madera.png",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig2",
    name: "fig2",
    textData: [
      {
        visible: true,
        rotation: 0,
        text: "Text",
        position: 0,
        name: "textTopWidthRef",
      },
      {
        visible: true,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: true,
        rotation: 0,
        text: "Text",
        position: 2,
        name: "textBottomWidthRef",
      },
      {
        visible: true,
        rotation: -90,
        text: "Text",
        position: 3,
        name: "textLeftHeighthRef",
      },
    ],
  },
];
