import { INIT_SHAPE_POINTS } from "./RECT_DATA_INIT";

// Config inicial 1 para encimera U
export const RECT_DATA_INIT_U_1 = [
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 1800,
    height: 600,
    fill: null,
    // fill: "grey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig1",
    name: "fig1",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 1400,
    height: 600,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig2",
    name: "fig2",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 1800,
    height: 600,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig3",
    name: "fig3",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
];

// Config inicial 2 para encimera U
export const RECT_DATA_INIT_U_2 = [
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 1200,
    height: 600,
    fill: null,
    // fill: "grey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig1",
    name: "fig1",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 2000,
    height: 600,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig2",
    name: "fig2",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 1800,
    height: 600,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig3",
    name: "fig3",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
];

// Config inicial 3 para encimera U
export const RECT_DATA_INIT_U_3 = [
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 1800,
    height: 600,
    fill: null,
    // fill: "grey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig1",
    name: "fig1",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 2000,
    height: 600,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig2",
    name: "fig2",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 1200,
    height: 600,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig3",
    name: "fig3",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
];

// Config inicial 4 para encimera U
export const RECT_DATA_INIT_U_4 = [
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 1200,
    height: 600,
    fill: null,
    // fill: "grey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig1",
    name: "fig1",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 2600,
    height: 600,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig2",
    name: "fig2",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
  {
    x: INIT_SHAPE_POINTS.x,
    y: INIT_SHAPE_POINTS.y,
    width: 1200,
    height: 600,
    fill: null,
    // fill: "lightgrey",
    stroke: "black",
    strokeWidth: 0,
    rotation: 0,
    cornerRadius: [0, 0, 0, 0],
    fillPatternImage: "/images/patron-roble_hickory.jpg",
    fillPatternRepeat: "repeat",
    fillPatternScaleX: 0.6,
    fillPatternScaleY: 0.3,
    id: "fig3",
    name: "fig3",
    textData: [
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textTopWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 200,
        rotation: 90,
        text: "Text",
        position: 1,
        name: "textRightHeighthRef",
      },
      {
        visible: false,
        x: 20,
        y: 300,
        rotation: 0,
        text: "Text",
        position: 1,
        name: "textBottomWidthRef",
      },
      {
        visible: false,
        x: 20,
        y: 20,
        rotation: -90,
        text: "Text",
        position: 1,
        name: "textLeftHeighthRef",
      },
    ],
  },
];
